# Generated by Django 3.0.4 on 2020-04-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('teacher', models.CharField(max_length=100)),
                ('SubjectField', models.CharField(max_length=200, null=True)),
                ('rating', models.IntegerField(max_length=1)),
            ],
        ),
    ]
