# Generated by Django 3.0.6 on 2020-05-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200506_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=5),
        ),
    ]
